version: '3.1'
networks:
  intraphp:

services:
  mysqldb:
    image: mysql:latest
    container_name: mysqlphpapp
    volumes:
      - ./datadir:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: passnotsecury
      MYSQL_DATABASE: loja1
      MYSQL_USER: stark
      MYSQL_PASSWORD: iAmIronMan
    ports:
      - "3306"
    networks: 
      intraphp:
        aliases:
          - mysqlphpapp
    deploy:
      restart_policy:
        condition: always
        delay: 10s

  phpweb:
    build:
      dockerfile: php.dockerfile
      context: .
    container_name: phpwebapp
    depends_on:
      - mysqldb
    volumes:
      - ./php/:/var/www/html/
    ports:
      - "80:80"
    links:
      - mysqldb
    stdin_open: true
    tty: true
    networks: 
      - intraphp
    deploy:
      restart_policy:
        condition: always
        delay: 10s
